# Generated by Django 4.2.5 on 2023-09-18 06:54

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_name', models.CharField(max_length=100)),
                ('Account_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=24)),
                ('version', models.IntegerField()),
                ('controls', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mqtt_device',
            fields=[
                ('device_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('general', 'ACCOUNT USER'), ('admin', 'ACCOUNT ADMIN')], default=(('general', 'ACCOUNT USER'), ('admin', 'ACCOUNT ADMIN')), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_type', models.CharField(max_length=100)),
                ('param_value', models.JSONField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mqtt_device')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.account')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, related_name='device_type', to='app.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='app.device')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_create', models.BooleanField(default=False)),
                ('User_edit', models.BooleanField(default=False)),
                ('User_views', models.BooleanField(default=False)),
                ('User_delete', models.BooleanField(default=False)),
                ('Account_create', models.BooleanField(default=False)),
                ('Account_edit', models.BooleanField(default=False)),
                ('Account_views', models.BooleanField(default=False)),
                ('Account_delete', models.BooleanField(default=False)),
                ('Device_create', models.BooleanField(default=False)),
                ('Device_edit', models.BooleanField(default=False)),
                ('Device_delete', models.BooleanField(default=False)),
                ('Device_views', models.BooleanField(default=False)),
                ('Device_instruction', models.BooleanField(default=False)),
                ('Setting', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.user'),
        ),
    ]
